"""
project_config.py — All project paths in one place.
Project : __PROJECT_NAME__
Created : auto-generated by pyCoreGage.create_project()

Edit the PROJECT_ROOT below if you move the project folder.
"""

import os
from pyCoreGage import CoreGageConfig

PROJECT_ROOT = "__PROJECT_ROOT__"

cfg = CoreGageConfig(
    project_name  = "__PROJECT_NAME__",
    rule_registry = os.path.join(PROJECT_ROOT, "rules", "config", "rule_registry.xlsx"),
    trial_checks  = os.path.join(PROJECT_ROOT, "rules", "trial"),
    study_checks  = os.path.join(PROJECT_ROOT, "rules", "study"),
    inputs        = os.path.join(PROJECT_ROOT, "inputs"),
    reports       = os.path.join(PROJECT_ROOT, "outputs", "reports"),
    feedback      = os.path.join(PROJECT_ROOT, "outputs", "feedback"),
)
