"""
run_coregage.py — Project driver script
Project : __PROJECT_NAME__
Created : auto-generated by pyCoreGage.create_project()

Run this script to execute all checks and generate reports:
    python run_coregage.py
"""

import logging
from pyCoreGage import (
    setup_coregage, load_inputs, run_checks, build_reports,
)
from rules.config.project_config import cfg

# Configure logging to match rCoreGage console style
logging.basicConfig(
    level=logging.INFO,
    format="%(message)s",
)


def coregage_run(cfg):
    print("=" * 50 + " pyCoreGage : Starting Run " + "=" * 50)
    print(f"  Project : {cfg.project_name}")

    state          = setup_coregage(cfg)
    state.domains  = load_inputs(cfg)
    print(f"   Domains: {', '.join(k.upper() for k in state.domains)}")
    state          = run_checks(cfg, state)
    build_reports(cfg, state)

    print("=" * 50 + " pyCoreGage : Run Complete " + "=" * 50)
    print(f">> Reports: {cfg.reports}")


if __name__ == "__main__":
    coregage_run(cfg)
